
var aNavContentDate = [
	[
		{
			url:"https://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"http://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		},
		{
			url:"http://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1799"
		}
	],
	[
		{
			url:"http://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1899"
		},
		{
			url:"http://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1899"
		}
	],
	[
		{
			url:"http://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1999"
		},
		{
			url:"http://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1999"
		},
		{
			url:"http://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1999"
		}
	],
	[
		{
			url:"http://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1899"
		},
		{
			url:"http://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1899"
		}
	],
	[
		{
			url:"http://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1899"
		},
		{
			url:"http://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1899"
		}
	],
	[
		{
			url:"http://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1999"
		},
		{
			url:"http://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1999"
		},
		{
			url:"http://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1999"
		}
	],
	[
		{
			url:"http://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1999"
		},
		{
			url:"http://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1999"
		},
		{
			url:"http://www.baidu.com",
			img:"images/shouji1.jpg",
			name:"小米CC9",
			price:"1999"
		}
	]
]

var aCateContentDate = [
	[
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机1-1"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机1-2"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机1-3"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机1-4"
		}
	],
	[
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-1"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-2"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-3"
		}
	],
	[
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机3-1"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机3-2"
		}
	],
	[
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机4-1"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机4-2"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机4-3"
		}
	],
	[
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机4-1"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机4-2"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机4-3"
		}
	],
	[
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-1"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-2"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-3"
		}
	],
	[
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-1"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-2"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-3"
		}
	],
	[
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-1"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-2"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-3"
		}
	],
	[
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-1"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-2"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-3"
		}
	],
	[
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-1"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-2"
		},
		{
			url:"http://www.tobao.com",
			img:"images/shouji1.jpg",
			name:"小米手机2-3"
		}
	]
]

var aTabContentDate = [
	[
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽前排",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			top:{
				desc:"米家电烤箱",
				price:"299",
				url:"https://www.baidu.com",
				img:"images/dkx.png"
			},
			bottom:{
				name:"热门",
				url:"https://www.baidu.com",
				img:"images/jiantou.png"
			}
		}
	],
	[
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽第二",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			top:{
				desc:"米家电烤箱",
				price:"299",
				url:"https://www.baidu.com",
				img:"images/dkx.png"
			},
			bottom:{
				name:"热门",
				url:"https://www.baidu.com",
				img:"images/jiantou.png"
			}
		}
	],
	[
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽第三",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			top:{
				desc:"米家电烤箱",
				price:"299",
				url:"https://www.baidu.com",
				img:"images/dkx.png"
			},
			bottom:{
				name:"热门",
				url:"https://www.baidu.com",
				img:"images/jiantou.png"
			}
		}
	],
	[
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽第四",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			url:"https://www.qq.com",
			img:"images/shangou1.jpg",
			name:"小米游戏本15.6 8代i5 8G 1T",
			desc: "冷酷的性能怪兽",
			price:"5999",
			del:"7999",
			flag:{
				name:"flag-jian",
				content:"立减200元"
			},
			comment:{
				content:"我是来做评论的哈哈哈哈哈哈哈哈哈",
				author:"shadiao"
			}
		},
		{
			top:{
				desc:"米家电烤箱",
				price:"299",
				url:"https://www.baidu.com",
				img:"images/dkx.png"
			},
			bottom:{
				name:"热门",
				url:"https://www.baidu.com",
				img:"images/jiantou.png"
			}
		}
	]
]